apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-db-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.secret.username | default "cG9zdGdyZXM=" | quote }}  # Base64 encoded: postgres
  password: {{ .Values.postgresql.secret.password | default "cGFzc3dvcmQ=" | quote }}  # Base64 encoded: password