apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "todo-app.fullname" . }}-network-policy
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "todo-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "todo-app.selectorLabels" . | nindent 10 }}
          app: frontend
    ports:
    - protocol: TCP
      port: 8000
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "todo-app.selectorLabels" . | nindent 10 }}
          app: postgresql
    ports:
    - protocol: TCP
      port: 5432
  - to: []  # Allow all external connections (DNS, external APIs, etc.)