apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "todo-app.fullname" . }}-quota
  namespace: todo-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    services.loadbalancers: "2"